# Generated by Django 4.2.7 on 2023-12-30 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_selected_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='selected_item',
        ),
    ]
