# Generated by Django 4.2.7 on 2024-01-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='method',
            field=models.CharField(default='COD', max_length=100),
        ),
    ]
