# Generated by Django 4.2.7 on 2024-01-05 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_cart_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
    ]
