# Generated by Django 4.2.7 on 2024-01-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_cart_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='pincode',
            field=models.IntegerField(blank=True, max_length=5, null=True),
        ),
    ]
