# Generated by Django 4.2.7 on 2024-01-06 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_orders_product_remove_orders_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
