# Generated by Django 4.2.7 on 2024-01-06 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy_now',
        ),
    ]
