# Generated by Django 4.2.7 on 2024-01-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_sizes_remove_cart_items_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_items',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sizes'),
        ),
    ]
